### ISSUE TITLE
Make Zoom Less Sensitive

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#106]
From JB:

The zoom feature is very fluid and sensitive to touch, and I am working on sensitizing my touch.  It's a challenge, but it might just take practice to overcome the challenge.  If not, can we "slow down" the zoom.  Basically, when I use the touch pad, the image zooms way too small or large.

**Comment by timdunn22** [comment]
## What does this issue do?
1. Makes the zoom on facsimile less sensitive

## How to test?
1. Login and go to https://mel-textlab.herokuapp.com/#documents/121
2. Click on a chapter and a leaf and make sure you can easily zoom in and out without it becoming too fast

**Comment by SteveMarvin** [comment]
This seems workable
