### ISSUE TITLE
Import is not preserving username of imported sequences from shared users.

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/textlab#144]
Example: BBChap06 Leaf 175 BBImage175SeqJR

![screen shot 2017-02-24 at 4 23 48 pm](https://cloud.githubusercontent.com/assets/18423533/23321478/ba321f9a-faad-11e6-9869-90d4f39e1efe.png)

**Comment by NickLaiacona** [comment]
I think this can be closed now that we have a mechanism for importing usernames.

**Comment by SteveMarvin** [comment]
Working and ACCEPTED
