### ISSUE TITLE
Panel border drag passes behind editing pane

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/textlab#149]
This is really a minor aesthetic issue, but I thought I'd toss it your way.

When one grabs and drags the border between the image pane and the editing pane, the border passes behind the editing pane toolbar and editing pane. 

In this first image you can see the border passing behind the tabs and buttons:
![border drag 01](https://cloud.githubusercontent.com/assets/18423533/23909995/abd96520-08ae-11e7-9003-5f150989f004.png)

In this second image you can't see the border at all, but I've dragged it down to where the arrow is pointing:

![border drag 02](https://cloud.githubusercontent.com/assets/18423533/23910036/c785663e-08ae-11e7-9a60-3c4a041c959a.png)

And in this last image, I've released it. It resizes normally where you let it go, so there is no real impairment of functionality, but it shouldn't be doing that. 

![border drag 03](https://cloud.githubusercontent.com/assets/18423533/23910079/eaac484e-08ae-11e7-94de-b9aaef3f65b1.png)

**Comment by tezcatlipoca** [comment]
Should be closed by #172

**Comment by SteveMarvin** [comment]
No dragging behind frame. 👍
