### ISSUE TITLE
Leaf pane popups appearing ~160 pixels to the left

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/textlab#150]
When one clicks on a region label in the Leaf display pane, the popup appears approximately 160 pixels to the left of the mouse cursor. 

![screen shot 2017-03-14 at 2 00 38 pm](https://cloud.githubusercontent.com/assets/18423533/23915188/bda71e86-08be-11e7-8420-cbe3d1bb4525.png)

**Comment by tezcatlipoca** [comment]
Note: load a leaf, resize the window an then click on an annotation (hypothesis: the notation popup location isn't updating on window resize)
