### ISSUE TITLE
Shared user can alter the step order of a submitted sequence

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/textlab#151]
Although a shared user cannot EDIT a sequence that has been submitted to the project owner, he can alter the step order, and it will be saved. The Project Owner will see the altered sequence order when next he opens the Sequence.

**Comment by tezcatlipoca** [comment]
Two states: share and submit object

**Share:** all read-only, write to owner
**Submit:** original owner read, project owner write

One may share a transcription or a sequence, when you share it everyone can see it

**Comment by tezcatlipoca** [comment]
@NickLaiacona  

I can lockdown the re-order drag, but I'm not sure I actually understand what functionality we're supposed to supply and what is not working as expected. I though that shared view should be read-only?

This is the shared edit view (left) and author view (right). What is the purpose of the "untitled" editor window at the bottom on the left? Related: does it make sense to provide shared users with an edit button in the first place if they can't edit (bottom)?



![screen shot 2017-11-13 at 8 23 58 pm](https://user-images.githubusercontent.com/1745781/32744693-b1897600-c8b0-11e7-9e9c-965cd9adfc81.png)
![screen shot 2017-11-13 at 8 25 48 pm](https://user-images.githubusercontent.com/1745781/32744761-eb0d4d20-c8b0-11e7-96eb-4b9be437da33.png)

**Comment by NickLaiacona** [comment]
So, first, the story above is referring to the steps in a secondary editing sequence, not the order of the leaves in the document tree. But yes, users who are not the owner of the project should not be able to reorder the leaves. All collaborators in the project can edit their own transcriptions of the leaves, they then can share these transcriptions with other members of the project and/or submit them to the project owner for publication. The untitled transcription window above is for creating such a transcription.  Nobody has a read only view of the entire edition except for unauthenticated web users who visit the URL of the published transcription.

**Comment by tezcatlipoca** [comment]
Super helpful - I'm now curious about where the "secondary editing sequence" takes place. Maybe just some steps to reproduce the bug? When I share a document I see from the share side that  I have "view" and "edit" options. View lets me see steps, but I can't edit them. Edit is an editor, but is there accidentally an editor under view in some cases?

**Comment by tezcatlipoca** [comment]
View only (I think, unless I missed an edit button)


![screen shot 2017-11-13 at 8 51 59 pm](https://user-images.githubusercontent.com/1745781/32745951-8947198c-c8b4-11e7-827f-6043e8ae8c56.png)
![screen shot 2017-11-13 at 8 52 08 pm](https://user-images.githubusercontent.com/1745781/32745952-895e66c8-c8b4-11e7-9c03-5733441c837f.png)

**Comment by NickLaiacona** [comment]
You pictures above are depicting the UI when a sequence has been published. The attached screenshot depicts the error state that is referred to in this story. When a sequence is shared with another user, the user should be able to view it in the editor but not change it. Here, the user can't change much, but they can change the order of the steps using the arrow button in the first column of the sequence table. Those arrow buttons should be hidden in this state.

<img width="1280" alt="shared sequence" src="https://user-images.githubusercontent.com/11439/32746590-285b8aac-c884-11e7-97a4-0b17d88287c6.png">

**Comment by tezcatlipoca** [comment]
Ah ha! thanks.
