### ISSUE TITLE
Implement SSL support for textlab.org

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#167]
On TextLab Staging, http://mel-textlab.herokuapp.com will redirect to https://mel-textlab.herokuapp.com. Verify the images display properly on staging under HTTPS. Once this story is delivered to production, verify that http://app.textlab.org redirects to https://app.textlab.org. Image should also display properly on production with image URLs pointing at HTTPS Image URLs

**Comment by SteveMarvin** [comment]
The server properly redirects to https, even when on a specific page within the domain. Attempting to change back to http fails. 👍

**Comment by SteveMarvin** [comment]
This has been good since SEP 2017 ;-)
