### ISSUE TITLE
Site Admin

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#169]
Users, when they create a new account, will be asked to select from a drop down which of the participating institutions they are associated with. At first, they will be able to select Hofstra, Performant, or US Air Force Academy. 

Once the user selects their institution and creates an account, the site admin(s) are notified. Site admins can then authorize that user and they are allowed to use the software. Site admins can  see a list of all the users associated with site. Site admins can archive users that they no longer wish to provide access. This will not erase data from that user, it just disables their account. Each institution will be able to have up to 30 user accounts activated at a given time. Users from TextLab 1.0 will be automatically associated with Hofstra and archived. 

Additionally:
* Text Lab Admins will be able to see a list of all users, as well as grant and revoke site admin privs. 
* Users that have been archived will see a screen indicating that their access is disabled.
* Users that are new and not yet enabled will see a screen telling them their access is under review.

**Comment by NickLaiacona** [comment]
@SteveMarvin , this is done except for the automated email messages. Could you please give it a spin?

**Comment by SteveMarvin** [comment]
This is all working (minus the emails), but there is a serious bug: New Users are admins by default #170
