### ISSUE TITLE
Resizing the transcription pane vertically triggers corresponding changes in the size of the image.

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#175]
Resizing the transcription pane vertically triggers corresponding changes in the size of the image. It would be better if image size remains independent of changes to the size of the transcription pane. Image size does appear to remain unchanged when the left sidebar is resized, so this setting just needs to be duplicated in the relationship between the image and transcription panes.

**Comment by timdunn22** [comment]
## What does this issue fix?
1. Resizing the transcription pane vertically triggers corresponding changes in the size of the image

## How to test 
1. Login and go to https://mel-textlab.herokuapp.com/#documents/121
2. Click on a chapter and a leaf
3. Make sure when you move the lower right pane up and down it does not resize the pane above it.
