### ISSUE TITLE
New links sometimes red?

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#179]
Bill Newmiller reports:

I was working with a student a short time ago and walked her through the process of linking from text to zone. The link created was red, but it worked fine. Later, I reloaded the page, and the link was blue. It remains functional.

**Comment by NickLaiacona** [comment]
@SteveMarvin can you reproduce this report? If so, please file under new issues.

**Comment by SteveMarvin** [comment]
Not seeing it.
