### ISSUE TITLE
Buttons on image pane don’t render icons in MSIE 11

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#180]
![screen shot 2017-11-09 at 3 40 31 pm](https://user-images.githubusercontent.com/11439/32628570-5679a18a-c564-11e7-838e-39a8e71c3bd6.png)

Also, there only 5 of them in MSIE. Not sure which one is missing. No tooltips are available in MSIE. In chrome tooltips display only for the zoom-in and zoom-out buttons.

**Comment by NickLaiacona** [comment]
Re-tested this on BrowserStack IE11 Windows 10, looked OK.

**Comment by SteveMarvin** [comment]
Working on latest version of IE Windows 10. 
![image](https://user-images.githubusercontent.com/18423533/44875982-ae457380-ac6d-11e8-951b-dd2947368134.png)
