### ISSUE TITLE
Make the facsimile display and the diplomatic resizable

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#182]
In the published view of the leaf, introduce a resizable split pane between the facsimile display and the diplomatic transcription.

**Comment by timdunn22** [comment]
## What this issue fixes?
1. Makes the facsimile display and the diplomatic resizable

## How to test?
1. Login and go to https://mel-textlab.herokuapp.com/transcriptions/16903
2. Make sure you are able to resize the facsimile (left side of the screen) and the diplomatic views (right side of the screen)

**Comment by SteveMarvin** [comment]
This has been good since June 4...
