### ISSUE TITLE
<restore> registers in diplo, but text is not restored in base version.

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#197]
Code to generate a base text does not know to undelete `<del>` tags inside `<restore>`.

**Comment by NickLaiacona** [comment]
here's a transcription that tests this fix:

> <milestone n="2" unit="chapter" />
<pb facs='#'/>
<ab>
  <lb/>This is normal text
  <lb/>This deletion should be <del rend="multi-stroke _ink1" hand="#HM" change="StA" facs="#act4-0004" >gone</del>.
  <lb/>This deletion should be <restore change="StBa" hand="#ESM" facs="#act4-0001" ><del rend="single-stroke _ink1" hand="#HM" change="StA" facs="#-0001" >present.</del></restore>
</ab>

**Comment by NickLaiacona** [comment]
test here: https://mel-textlab-pr-198.herokuapp.com/

**Comment by SteveMarvin** [comment]
Both "gone" and "present" are gone.

![screen shot 2017-12-07 at 11 40 02 am](https://user-images.githubusercontent.com/18423533/33726593-6cef7850-db43-11e7-9084-f168a071cab9.png)

**Comment by NickLaiacona** [comment]
interesting, could you make this project public and share a link with me?

**Comment by SteveMarvin** [comment]
TL link: https://mel-textlab.herokuapp.com:/document_sections/1013.html.
JE link: http://juxta-editions-staging.herokuapp.com:443/editions/97/live

@NickLaiacona

**Comment by NickLaiacona** [comment]
this code is only deployed here: https://mel-textlab-pr-198.herokuapp.com/ , that's why you aren't seeing the fix. :^)

**Comment by SteveMarvin** [comment]
Looks good! 👍
