### ISSUE TITLE
Vertical resize scrambles the zone links

### ISSUE THREAD

**Issue by tezcatlipoca** [performant-software/textlab#201]
![screen shot 2017-12-07 at 7 45 29 pm](https://user-images.githubusercontent.com/1745781/33732562-34171c1a-db87-11e7-96c4-52d701ddd8e2.png)

**Comment by SteveMarvin** [comment]
This cannot be tested in PR-202 because there are no zone links.

**Comment by SteveMarvin** [comment]
This looks good in 202 now.
