### ISSUE TITLE
Sequencing Oddity

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#210]
The steps of revision sequence SeqBP24Conflict1JB in TL2's edit view are in the right order, but they are in reverse order in Preview. I tried moving things around, and then back to their proper order, but that led to another order, and I refreshed often.  This has never happened before.

Once again, though, the sequencing of steps, which appears in proper order in TextLab, is screwed upon in Juxta Eds.  I can't seem to make out how the steps are resequenced: in this eleven step revision several steps are in order but the others are not, including step 1, which appears at the next to last.

**Comment by NickLaiacona** [comment]
Not sure what's happening in either of these reports. The sequence referenced above looks to be in the correct order: https://app.textlab.org/transcriptions/17453

**Comment by NickLaiacona** [comment]
@SteveMarvin can you reproduce a condition where sequences are out of order when published?

**Comment by NickLaiacona** [comment]
nevermind, I found an example of this.

**Comment by SteveMarvin** [comment]
@NickLaiacona  I'm not seeing any obvious misordering in sequences in those documents to which I have access. I'm passing this one.
