### ISSUE TITLE
Diplo Horizontal scroll bar

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#215]
Provide a horizontal scroll bar for long line in the diplomatic rendering instead of wrapping lines in the published diplomatic.

**Comment by NickLaiacona** [comment]
Introducing the split pane view makes it possible to see long lines now. Lines no longer wrap.

**Comment by SteveMarvin** [comment]
Well, you can on a sufficiently narrow screen, but it does work. ;-)

**Comment by timdunn22** [comment]
@jamiefolsom This is not necessary given Issue #219 solves this problem
