### ISSUE TITLE
Zones per transcription

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/textlab#223]
If one attempts to delete a zone that has been referenced in a transcription, a warning appears indicating what other transcriptions reference this zone. The user would have to confirm to delete a zone that is referenced in a transcription

**Comment by timdunn22** [comment]
## What this issue fixes?
1. Shows a warning message when a user deletes a zone.

## How to test?
1. Login and go to https://mel-textlab.herokuapp.com/#documents/121
2. Click on a chapter one icon and then click on any leaf below it.
3. Click on a zone (a blue outlined box inside the image) click on the red dot in the upper right hand corner of the image.
4. A Message should pop up asking if you want to delete the zone or not.
