### ISSUE TITLE
Image Download

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/textlab#224]
TextLab will provide a button that allows the user to download a copy of the facsimile currently being viewed.

**Comment by timdunn22** [comment]
## What this issue fixes?
1. Enables the user to download the facsimile on the documents show page.

## How to test?
1. Login and go to https://mel-textlab.herokuapp.com/#documents/121
2. Click on any chapter then click on any leaf
3. On the upper right pane there is a download button in the upper right hand corner click on it
4. An image should download

**Comment by SteveMarvin** [comment]
Working! However, I note that it is named default.jpg. That could unwieldy if the user wants to download multiple pages.
