### ISSUE TITLE
Restore Tag Base Text Display

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/textlab#226]
Place a dotted blue underline beneath restored text. Remove strikethrough for deleted text that was restored.

**Comment by timdunn22** [comment]
## What does this issue accomplish?
1. Restored text is now shown with a dotted blue line

## How to test?
1. Login and go to https://mel-textlab.herokuapp.com/#documents/121
2. Click on a chapter and a leaf
3. A blue dotted line should be shown for any change that has restored text
