### ISSUE TITLE
CORS issue with IIIF Image

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/textlab#228]
See js console on: https://mel-textlab.herokuapp.com/#documents/90

**Comment by timdunn22** [comment]
## What does this issue resolve?
1. Fixes a cores javascript console error

## How to test?
1. Login and go to https://mel-textlab.herokuapp.com/#documents/90
2. Check to see if there are any errors in the js console

**Comment by SteveMarvin** [comment]
Errors in console:
![image](https://user-images.githubusercontent.com/18423533/88699673-a00c6600-d0d5-11ea-9197-9cd15d511134.png)

**Comment by SteveMarvin** [comment]
No more errors, although the warnings are still there. 
![image](https://user-images.githubusercontent.com/18423533/89305816-1b719880-d63d-11ea-83ce-a484b9b6bf7e.png)
