### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/textlab#6]
The purpose of this epic is to transition from using email addresses to usernames and real names to identify users in TextLab.

The user's username is displayed on the login bar, on share files, and on published leaves and on sequences. 

During account creation, in addition to an email and password, the user can specify a username, first name, and last name for their account. Usernames and email must be unique to the user.

During account creation, the user's email is verified via email. 

Account Dialog
------

The account dialog is accessed by clicking on the user's username in the upper right hand corner of the screen. This modal dialog allows the user to change their username, first name, and last name. The user can also update their email and password using this dialog. Changing one's email requires email based verification.

Changes to Edit Settings Dialog
------

Users that are part of the project should be listed by first and last name, with their username in parens. Example: Nick Laiacona (nick) 

The user's email address should not be displayed. Also, one should invite users based on their username, not email.

**Comment by tezcatlipoca** [comment]
Todo: "During account creation, the user's email is verified via email."
