### ISSUE TITLE
Published thumbnails failing

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/textlab#84]
When I publish a transcript with verified XML to a project that has the Publish option checked, I can see that on the published site. However, the thumbnail for the leaf is broken. If I click the broken thumbnail, I am taken to a working version of the leaf image and transcript.

Test case: 
* Account: nick@performantsoftware.com
* Project: Thumbnail fail (sb/b6)
* Tree folder: sb
* Leaf: b6
* Published URL of broken thumbnail: http://mel-textlab.herokuapp.com/document_sections/31 

![broken thumbnail](https://cloud.githubusercontent.com/assets/18423533/20183439/51d6b6a4-a733-11e6-8b5e-40f3ffd6fec9.png)

**Comment by NickLaiacona** [comment]
Can we close this?

**Comment by SteveMarvin** [comment]
We can!
